### ISSUE TITLE
Not allow pumping when transfer = NONE

### ISSUE THREAD

**Issue by Gordon-Dry** [henrybauer/GPOSpeedPump#2]
Actually GPOSpeedFuelPump allows pumping when _flowMode_ is anything else than **NO_FLOW**.

But the state of _transfer_ is not taken into account, so a resource with **transfer = NONE** is pumped.

So I request to disallow pumping of resources which are flagged with **transfer = NONE**, no matter what the _flowMode_ is.

**Comment by henrybauer** [comment]
This confused me at first because it's named "transfer" in the config file but "resourceTransferMode" in code.  Anyways, looks like you're talking about "Shielding" here: https://github.com/Gordon-Dry/Kerbalism/blob/master/GameData/Kerbalism/System/Resources.cfg

Currently GPOSpeedFuelPump checks PartResourceDefinition.resourceFlowMode ("flowMode") is not NO_FLOW or NULL.

    NO_FLOW = 0,
    ALL_VESSEL = 1,
    STAGE_PRIORITY_FLOW = 2,
    STACK_PRIORITY_SEARCH = 3,
    ALL_VESSEL_BALANCE = 4,
    STAGE_PRIORITY_FLOW_BALANCE = 5,
    STAGE_STACK_FLOW = 6,
    STAGE_STACK_FLOW_BALANCE = 7,
    NULL = 8

TAC checks PartResourceDefinition.resourceTransferMode ("transfer") is set to PUMP.

    NONE = 0,
    DIRECT = 1,
    PUMP = 2

Both check if the resource in that part is locked (the green triangle, AKA PartResource.flowState).

It's no big deal to check resourceTransferMode as well, but...  why would you have a resource that allows flowing, but not transferring?

**Comment by Gordon-Dry** [comment]
I would say something along the lines of because the nature of the resources in question are tied to a habitation process, such as an Atmosphere resource inside the habitable areas of a vessel, they need the capability of being allowed to flow throughout the vessel as they are simulating a resource that is not in a tank but inside the living space of the vessel and thus cannot be transferred by pumps as the resource is free flowing throughout the vessel.
Regarding shielding the resource is simulating lead sheets bolted to the walls etc of a vessel, the tweakable slider simulates the thickness of the sheets.
This resource needs to flow because the shielding from parts that have the resource fitted is averaged over the whole vessel, the reason this resource is averaged over the vessel is due to how Kerbalism calculates background processing of unloaded vessels, it is unable to detect what parts the crew are in and thus the resource needs to flow throughout the vessel to protect the crew from radiation but not be transferable because it is bolted down.

**Comment by henrybauer** [comment]
This is fixed in 1.8.14

**Comment by Gordon-Dry** [comment]
Confirmed by testing it without the quick'n'dirty Shielding fix mentioned above in Kerbalism.
